### ISSUE TITLE
Is there a project file available?

### ISSUE THREAD

**Issue by wonea** [brenosilver/CityFuture#2]
I could add one, as I'm keen try out your code.

**Comment by brenosilver** [comment]
Hey! Thank you for the interest. Unfortunately you wont be able to do much as of right now, mostly because there isn't much implemented yet, nor there are any models (I'm useless with 3D modelling).

I'm making this project for learning purposes only, to practice and learn more advanced techniques for my undergraduate CS degree. Even though I work almost every day on this during free hours, I do not guarantee a quality final product nor I do guarantee it will even get to be a final product.

 If you identify with this and want to contribute I would be glad to send you a project file.

**Comment by wonea** [comment]
That would be fine, I would like to build the project. I was browsing a GitHub for interesting projects to possibly learn game design, and find a small C# project to contribute against. I'm a dev with about 5+ years experience mostly in C# (a little C++ too), by day I write mostly web services, libraries, and desktop applications.

**Comment by brenosilver** [comment]
That's great, I've just sent you the link for the project folder to your email.

**Comment by wonea** [comment]
Thanks for the file, I'll have a play around with it.
